# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            wiks.wiki
tagline:          "The personal is personal."
description:      "The experience of being a person varies so aggressively— I want to use the internet for one of its more innocent purposes: to learn about one another and to gradually accept and understand the common truths between our lives."
url:              https://wiks.wiki
baseurl:          
author:           ""
name:             "WIKS"
excerpt_separator: "<!-- more -->"
twitter :		  R4D14NT_W1K5

paginate:         3

# Custom vars
version:          2.1.0
repo:           https://github.com/poole/hyde

# Plugins/Gems
plugins:          [jekyll-paginate, jekyll-seo-tag, jekyll-last-modified-at, jekyll-sitemap]
last-modified-at:
    date-format: '%d-%b-%y'

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: wiks-wiki